/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // BoardTAU Green Theme - used by default
        primary: 'oklch(var(--color-primary) / <alpha-value>)',
        'primary-foreground': 'oklch(var(--color-primary-foreground) / <alpha-value>)',
        secondary: 'oklch(var(--color-secondary) / <alpha-value>)',
        'secondary-foreground': 'oklch(var(--color-secondary-foreground) / <alpha-value>)',
        accent: 'oklch(var(--color-accent) / <alpha-value>)',
        'accent-foreground': 'oklch(var(--color-accent-foreground) / <alpha-value>)',
        background: 'oklch(var(--color-background) / <alpha-value>)',
        foreground: 'oklch(var(--color-foreground) / <alpha-value>)',
        card: 'oklch(var(--color-card) / <alpha-value>)',
        'card-foreground': 'oklch(var(--color-card-foreground) / <alpha-value>)',
        popover: 'oklch(var(--color-popover) / <alpha-value>)',
        'popover-foreground': 'oklch(var(--color-popover-foreground) / <alpha-value>)',
        muted: 'oklch(var(--color-muted) / <alpha-value>)',
        'muted-foreground': 'oklch(var(--color-muted-foreground) / <alpha-value>)',
        destructive: 'oklch(var(--color-destructive) / <alpha-value>)',
        'destructive-foreground': 'oklch(var(--color-destructive-foreground) / <alpha-value>)',
        border: 'oklch(var(--color-border) / <alpha-value>)',
        input: 'oklch(var(--color-input) / <alpha-value>)',
        ring: 'oklch(var(--color-ring) / <alpha-value>)',
        sidebar: 'oklch(var(--color-sidebar) / <alpha-value>)',
        'sidebar-foreground': 'oklch(var(--color-sidebar-foreground) / <alpha-value>)',
        'sidebar-primary': 'oklch(var(--color-sidebar-primary) / <alpha-value>)',
        'sidebar-primary-foreground': 'oklch(var(--color-sidebar-primary-foreground) / <alpha-value>)',
        'sidebar-accent': 'oklch(var(--color-sidebar-accent) / <alpha-value>)',
        'sidebar-accent-foreground': 'oklch(var(--color-sidebar-accent-foreground) / <alpha-value>)',
        'sidebar-border': 'oklch(var(--color-sidebar-border) / <alpha-value>)',
        'sidebar-ring': 'oklch(var(--color-sidebar-ring) / <alpha-value>)',
        chart: {
          1: 'oklch(var(--color-chart-1) / <alpha-value>)',
          2: 'oklch(var(--color-chart-2) / <alpha-value>)',
          3: 'oklch(var(--color-chart-3) / <alpha-value>)',
          4: 'oklch(var(--color-chart-4) / <alpha-value>)',
          5: 'oklch(var(--color-chart-5) / <alpha-value>)',
        },
      },
      fontFamily: {
        sans: ['var(--font-sans)', 'system-ui', 'sans-serif'],
        mono: ['var(--font-mono)', 'monospace'],
        serif: ['var(--font-serif)', 'serif'],
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
      },
      boxShadow: {
        '2xs': 'var(--shadow-2xs)',
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        hover: 'var(--shadow-hover)',
      },
      letterSpacing: {
        tighter: 'var(--tracking-tighter)',
        tight: 'var(--tracking-tight)',
        normal: 'var(--tracking-normal)',
        wide: 'var(--tracking-wide)',
        wider: 'var(--tracking-wider)',
        widest: 'var(--tracking-widest)',
      },
      fontSize: {
        hero: ['clamp(2.25rem, 5vw, 3.5rem)', { lineHeight: '1.15', letterSpacing: '-0.02em' }],
        section: ['1.5rem', { lineHeight: '1.3', letterSpacing: '-0.01em' }],
        'body-lg': ['1.0625rem', { lineHeight: '1.6' }],
      },
      backdropBlur: {
        xs: '2px',
        glass: '20px',
        'glass-xl': '24px',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'hero-gradient': 'linear-gradient(135deg, var(--tw-gradient-stops))',
      },
      borderRadius: {
        card: '16px',
        input: '12px',
        pill: '9999px',
      },
      transitionTimingFunction: {
        smooth: 'cubic-bezier(0.4, 0, 0.2, 1)',
        bounce: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        apple: 'cubic-bezier(0.25, 0.46, 0.45, 0.94)',
      },
      animation: {
        gradient: 'gradient 8s ease infinite',
        float: 'float 6s ease-in-out infinite',
        shimmer: 'shimmer 1.5s ease-in-out infinite',
      },
      keyframes: {
        gradient: {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
      backgroundSize: {
        'gradient-large': '200% 200%',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
