'use client';

import React from 'react';
import { motion } from 'framer-motion';
import { cn } from '@/lib/utils';
import { AreaChart, Area, ResponsiveContainer } from 'recharts';
import { 
  IconBuildingCommunity,
  IconUsers,
  IconStar,
  IconHomeHeart
} from '@tabler/icons-react';
import { ArrowUpRight, ArrowDownRight, Minus } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/app/admin/components/ui/card';
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/app/admin/components/ui/tooltip';

interface DirectoryKPICardsProps {
  isLoading?: boolean;
}

export function DirectoryKPICards({ isLoading }: DirectoryKPICardsProps) {
  // Using hardcoded mock data similar to previous implementation, 
  // but upgraded for the advanced chart format.
  const kpis = [
    { 
      label: 'Total Units', 
      value: '1,428', 
      icon: IconBuildingCommunity, 
      color: 'text-violet-500', 
      bg: 'bg-violet-500/10', 
      chartColor: '#8b5cf6', 
      trendData: [{v: 1200}, {v: 1250}, {v: 1280}, {v: 1350}, {v: 1380}, {v: 1400}, {v: 1428}],
      trend: { label: '+12%', direction: 'up', color: 'text-emerald-500', bg: 'bg-emerald-500/10', icon: ArrowUpRight },
      tooltip: {
        title: 'Total Active Units',
        description: 'The overall number of individual rentable units across all listed properties.',
        detail: 'Excludes archived or delisted properties.'
      }
    },
    { 
      label: 'Global Occupancy', 
      value: '94.2%', 
      icon: IconUsers, 
      color: 'text-blue-500', 
      bg: 'bg-blue-500/10', 
      chartColor: '#3b82f6', 
      trendData: [{v: 85}, {v: 88}, {v: 86}, {v: 90}, {v: 92}, {v: 93}, {v: 94.2}],
      trend: { label: '+2.1%', direction: 'up', color: 'text-emerald-500', bg: 'bg-emerald-500/10', icon: ArrowUpRight },
      tooltip: {
        title: 'Platform Occupancy Rate',
        description: 'Percentage of all available units that are currently occupied by tenants.',
        detail: 'Aim for >90% to maintain high profitability.'
      }
    },
    { 
      label: 'Avg Platform Rating', 
      value: '4.85', 
      icon: IconStar, 
      color: 'text-amber-500', 
      bg: 'bg-amber-500/10', 
      chartColor: '#f59e0b', 
      trendData: [{v: 4.5}, {v: 4.6}, {v: 4.65}, {v: 4.7}, {v: 4.8}, {v: 4.82}, {v: 4.85}],
      trend: { label: 'Top 1%', direction: 'up', color: 'text-amber-500', bg: 'bg-amber-500/10', icon: ArrowUpRight },
      tooltip: {
        title: 'Average Property Rating',
        description: 'The aggregated mean rating across all property reviews on the platform.',
        detail: '4.85 is considered exceptional performance.'
      }
    },
    { 
      label: 'RevPAR (Daily)', 
      value: '₱2,450', 
      icon: IconHomeHeart, 
      color: 'text-emerald-500', 
      bg: 'bg-emerald-500/10', 
      chartColor: '#10b981', 
      trendData: [{v: 2100}, {v: 2150}, {v: 2100}, {v: 2200}, {v: 2350}, {v: 2400}, {v: 2450}],
      trend: { label: '+15.2%', direction: 'up', color: 'text-emerald-500', bg: 'bg-emerald-500/10', icon: ArrowUpRight },
      tooltip: {
        title: 'Revenue Per Available Room',
        description: 'The average daily revenue generated by each rentable unit.',
        detail: 'A key performance metric in the hospitality sector.'
      }
    }
  ];

  return (
    <TooltipProvider delayDuration={200}>
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-4">
        {kpis.map((stat, i) => {
          const TrendIcon = isLoading ? Minus : stat.trend.icon;
          return (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.08 }}
            >
              <Tooltip>
                <TooltipTrigger asChild>
                  <Card className="cursor-default border-none bg-white/40 dark:bg-gray-900/40 backdrop-blur-xl shadow-lg rounded-[2rem] overflow-hidden group h-full transition-all hover:bg-white/50 dark:hover:bg-gray-900/50 hover:shadow-2xl hover:-translate-y-0.5">
                    <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
                      <CardTitle className="text-[10px] font-black uppercase tracking-widest text-gray-500 dark:text-gray-400">
                        {stat.label}
                      </CardTitle>
                      <div className={cn("p-3 rounded-2xl transition-transform group-hover:scale-110", stat.bg)}>
                        <stat.icon className={cn("h-5 w-5", stat.color)} />
                      </div>
                    </CardHeader>
                    <CardContent>
                      <div className="text-3xl font-black tabular-nums text-gray-900 dark:text-white tracking-tighter truncate">
                        {isLoading ? (
                          <div className="h-9 w-24 bg-muted/50 dark:bg-white/10 animate-pulse rounded-xl" />
                        ) : (
                          stat.value
                        )}
                      </div>
                      <div className="flex flex-col gap-1 items-start bg-transparent mt-2">
                        <div className="flex items-center flex-wrap gap-1.5">
                          <div className={cn(
                            "flex items-center gap-1.5 w-fit px-2 py-1 rounded-lg",
                            isLoading ? "bg-gray-100 dark:bg-gray-800" : stat.trend.bg
                          )}>
                            {isLoading ? (
                              <>
                                <TrendIcon className="w-3 h-3 text-gray-400" />
                                <div className="h-2.5 w-8 bg-gray-200 dark:bg-gray-700 animate-pulse rounded" />
                              </>
                            ) : (
                              <>
                                <TrendIcon className={cn("w-3 h-3", stat.trend.color)} />
                                <span className={cn("text-[9px] font-bold uppercase tracking-widest", stat.trend.color)}>
                                  {stat.trend.label}
                                </span>
                              </>
                            )}
                          </div>
                          <span className="text-[9px] text-gray-400 font-bold uppercase tracking-widest bg-gray-50 dark:bg-gray-800/50 px-2 py-1 rounded-lg">
                            vs last period
                          </span>
                        </div>
                      </div>
                      <div className="h-20 w-full mt-6 -mx-6 mb-[-1.5rem]">
                        <ResponsiveContainer width="100%" height="100%">
                          <AreaChart data={isLoading ? [{v:0},{v:0},{v:0}] : stat.trendData}>
                            <defs>
                              <linearGradient id={`gradient-dir-${i}`} x1="0" y1="0" x2="0" y2="1">
                                <stop offset="0%" stopColor={stat.chartColor} stopOpacity={0.25} />
                                <stop offset="100%" stopColor={stat.chartColor} stopOpacity={0} />
                              </linearGradient>
                            </defs>
                            <Area
                              type="monotone"
                              dataKey="v"
                              stroke={stat.chartColor}
                              strokeWidth={3}
                              fill={`url(#gradient-dir-${i})`}
                              isAnimationActive={true}
                              animationDuration={1500}
                              animationEasing="ease-out"
                            />
                          </AreaChart>
                        </ResponsiveContainer>
                      </div>
                    </CardContent>
                  </Card>
                </TooltipTrigger>
                <TooltipContent
                  side="bottom"
                  className="max-w-[220px] p-0 border-0 shadow-2xl rounded-2xl overflow-hidden"
                >
                  <div className="bg-white/95 dark:bg-gray-900/95 backdrop-blur-xl border border-gray-100 dark:border-gray-800 rounded-2xl p-4 space-y-2">
                    <div className="flex items-center gap-2">
                      <div className={cn("p-1.5 rounded-lg", stat.bg)}>
                        <stat.icon className={cn("h-3.5 w-3.5", stat.color)} />
                      </div>
                      <span className="text-xs font-black text-gray-900 dark:text-white uppercase tracking-widest">
                        {stat.tooltip.title}
                      </span>
                    </div>
                    <p className="text-[11px] text-gray-500 dark:text-gray-400 leading-relaxed">
                      {stat.tooltip.description}
                    </p>
                    <div className="pt-1 border-t border-gray-100 dark:border-gray-800">
                      <p className="text-[10px] font-bold text-gray-400 dark:text-gray-500">
                        {stat.tooltip.detail}
                      </p>
                    </div>
                  </div>
                </TooltipContent>
              </Tooltip>
            </motion.div>
          );
        })}
      </div>
    </TooltipProvider>
  );
}
