/**
 * Security Token Utility for Obfuscating and Signing Restriction URLs
 * Protects PII (emails) and prevents URL tampering/enumeration.
 */

const TOKEN_SECRET = process.env.NEXTAUTH_SECRET || "boardtau-security-token-secret-fallback";
const TOKEN_TTL_MS = 24 * 60 * 60 * 1000; // 24 hours

export interface RestrictionTokenPayload {
  email: string;
  reason: 'suspended' | 'banned' | string;
  exp: number;
}

/**
 * Encrypts payload string using a key-derived stream cipher
 */
function encryptBytes(text: string, secretKey: string): string {
  const textBytes = new TextEncoder().encode(text);
  const keyBytes = new TextEncoder().encode(secretKey);

  // Generate 31-bit positive random salt
  const salt = Math.floor(Math.random() * 0x7fffffff);
  const result: number[] = [
    (salt >>> 24) & 0xff,
    (salt >>> 16) & 0xff,
    (salt >>> 8) & 0xff,
    salt & 0xff,
  ];

  for (let i = 0; i < textBytes.length; i++) {
    const keyIndex = (((i + salt) % keyBytes.length) + keyBytes.length) % keyBytes.length;
    const keyByte = keyBytes[keyIndex];
    result.push(textBytes[i] ^ keyByte);
  }

  // Convert to base64url
  let binString = '';
  for (let i = 0; i < result.length; i++) {
    binString += String.fromCharCode(result[i]);
  }

  if (typeof btoa === 'function') {
    return btoa(binString).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
  }
  return Buffer.from(result).toString('base64url');
}

/**
 * Decrypts a token generated by encryptBytes
 */
function decryptBytes(token: string, secretKey: string): string | null {
  try {
    let base64 = token.replace(/-/g, '+').replace(/_/g, '/');
    while (base64.length % 4) base64 += '=';

    let bytes: number[] = [];
    if (typeof atob === 'function') {
      const binString = atob(base64);
      for (let i = 0; i < binString.length; i++) {
        bytes.push(binString.charCodeAt(i));
      }
    } else {
      bytes = Array.from(Buffer.from(base64, 'base64'));
    }

    if (bytes.length < 5) return null;

    const salt = (((bytes[0] & 0x7f) << 24) | (bytes[1] << 16) | (bytes[2] << 8) | bytes[3]) >>> 0;
    const keyBytes = new TextEncoder().encode(secretKey);
    const decryptedBytes: number[] = [];

    for (let i = 4; i < bytes.length; i++) {
      const offset = i - 4;
      const keyIndex = (((offset + salt) % keyBytes.length) + keyBytes.length) % keyBytes.length;
      const keyByte = keyBytes[keyIndex];
      decryptedBytes.push(bytes[i] ^ keyByte);
    }

    return new TextDecoder().decode(new Uint8Array(decryptedBytes));
  } catch (err) {
    return null;
  }
}

/**
 * Creates an encrypted security token for restriction pages.
 */
export function createRestrictionToken(email: string, reason: 'suspended' | 'banned' | string): string {
  const payload: RestrictionTokenPayload = {
    email: email.trim().toLowerCase(),
    reason,
    exp: Date.now() + TOKEN_TTL_MS,
  };
  return encryptBytes(JSON.stringify(payload), TOKEN_SECRET);
}

/**
 * Verifies and decrypts an encrypted restriction token.
 * Returns payload if valid & unexpired, otherwise null.
 */
export function verifyRestrictionToken(token?: string | null): RestrictionTokenPayload | null {
  if (!token) return null;
  try {
    const jsonStr = decryptBytes(token, TOKEN_SECRET);
    if (!jsonStr) return null;

    const payload: RestrictionTokenPayload = JSON.parse(jsonStr);
    if (!payload || !payload.email || !payload.exp) return null;

    // Check expiration
    if (payload.exp < Date.now()) {
      return null;
    }

    return payload;
  } catch (err) {
    return null;
  }
}
