import {
  IconAlertTriangle,
  IconArrowRight,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconPhoto,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconProps,
  IconShoppingBag,
  IconMoon,
  IconDotsVertical,
  IconPizza,
  IconPlus,
  IconSettings,
  IconSun,
  IconTrash,
  IconBrandTwitter,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconX,
  IconLayoutKanban,
  IconBrandGithub,
  IconFolder,
  IconUsers,
  IconCrown,
  IconStar,
  IconBox,
  IconPalette,
  IconShield,
  IconShieldCheck,
  IconShieldHeart,
  IconChartBar,
  IconChartLine,
  IconCurrencyDollar,
  IconReceipt,
  IconHome,
  IconBuilding,
  IconCalendar,
  IconTag,

  IconServer,
  IconDatabase,
  IconApi,
  IconHeartbeat,
  IconList,
  IconFlag,
  IconMail,
  IconUserCheck,
  IconBell,
  IconClock,
  IconAlertCircle,
  IconExternalLink
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons: Record<string, Icon> = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconBox,
  palette: IconPalette,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  workspace: IconFolder,
  teams: IconUsers,
  pro: IconCrown,
  exclusive: IconStar,
  account: IconUserCircle,
  profile: IconUser,

  // Enterprise features icons
  users: IconUsers,
  shield: IconShield,
  shieldCheck: IconShieldCheck,
  shieldAlert: IconShieldHeart,
  chartBar: IconChartBar,
  chartLine: IconChartLine,
  currencyDollar: IconCurrencyDollar,
  receipt: IconReceipt,
  home: IconHome,
  building: IconBuilding,
  calendar: IconCalendar,
  tag: IconTag,
  monitor: IconDeviceLaptop,
  server: IconServer,
  database: IconDatabase,
  api: IconApi,
  heartbeat: IconHeartbeat,
  list: IconList,
  flag: IconFlag,
  mail: IconMail,
  userCheck: IconUserCheck,
  notification: IconBell,
  clock: IconClock,
  alertCircle: IconAlertCircle,
  externalLink: IconExternalLink
};
