'use client';

import React, { useState, useEffect } from 'react';
import { useTheme } from 'next-themes';
import { Search, UserCircle, CreditCard, ShieldCheck, Settings, ArrowRight, ChevronDown, Bot, Map, Loader2, X } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import Link from 'next/link';
import { GlowingCards, GlowingCard } from '@/components/lightswind/glowing-cards';

// Detailed Articles Extracted from the Capstone Thesis & System Business Rules
const allArticles = [
  // PLATFORM SECURITY & KYC
  {
    category: 'Platform Security & KYC',
    title: 'What is the Identity Verification (KYC) process?',
    content: 'BoardTAU implements a strict Know Your Customer (KYC) protocol to ensure all users (tenants and landlords) are legitimate. We use Google MediaPipe for biometric Liveness Detection. This means during verification, you will be asked to perform real-time facial movements (like blinking or turning your head) to prove you are a real human and not just a static photograph. This prevents fraudulent accounts and protects the community.',
  },
  {
    category: 'Platform Security & KYC',
    title: 'What legal documents are required to become a Host/Landlord?',
    content: 'To ensure the safety of our student tenants, all landlords must submit legal documentation. During the Host Application process, you must upload: 1) A valid Business Permit (Latest Mayor\'s Permit or SEC/DTI Registration). 2) A valid Fire Safety Inspection Certificate from the Bureau of Fire Protection (BFP). The Fire Safety Certificate is strictly mandatory for all student accommodations on BoardTAU. Once submitted, our admins review and approve your application within 24-48 hours.',
  },
  {
    category: 'Platform Security & KYC',
    title: 'How does BoardTAU protect my messages and data?',
    content: 'All real-time communications between tenants and property owners are powered by Pusher WebSockets and secured using AES-256-GCM encryption. This ensures that your private conversations, inquiries, and personal details remain confidential and are protected against unauthorized interception.',
  },
  {
    category: 'Platform Security & KYC',
    title: 'Who is allowed to leave a rating or review?',
    content: 'To prevent fake reviews and maintain platform integrity, BoardTAU enforces a strict closed-loop review system. Tenants who are currently checked-in cannot leave a review yet. You can only leave a review after you have completely moved out of the room, and the landlord has manually updated your reservation status to "COMPLETED" in their dashboard.',
  },
  {
    category: 'Platform Security & KYC',
    title: 'How does BoardTAU protect my account password?',
    content: 'Your security is our priority. We use robust authentication powered by NextAuth.js. Your passwords are heavily encrypted using bcrypt before being stored in our database. We also support secure third-party logins (like Google OAuth) so you can access your account without creating a new password.',
  },
  {
    category: 'Platform Security & KYC',
    title: 'What should I do if I suspect a fake listing?',
    content: 'If a listing seems suspicious or requests payments outside of the BoardTAU platform, please report it immediately using the "Report Listing" button. Our Trust & Safety admin team will temporarily freeze the listing and investigate the landlord\'s submitted business permits and KYC logs.',
  },
  {
    category: 'Platform Security & KYC',
    title: 'Can I use a relative\'s ID for verification?',
    content: 'No. The ID you upload must strictly match the person taking the real-time biometric scan. Our MediaPipe Liveness Detection system ensures that the person operating the camera is the exact same person shown on the valid government ID to prevent identity theft.',
  },

  // PAYMENTS & BILLING
  {
    category: 'Payments & Billing',
    title: 'How do I pay my reservation fee securely?',
    content: 'BoardTAU uses a dual-gateway strategy for maximum flexibility and security. You can pay your reservation fees using Credit/Debit cards via our Stripe integration, or through local Philippine e-wallets like GCash and Maya via our PayMongo integration. Both gateways utilize webhook-based verification so your payment is instantly and securely recorded in our database without manual intervention.',
  },
  {
    category: 'Payments & Billing',
    title: 'How do I prove my reservation when I arrive?',
    content: 'Once your reservation fee is paid and confirmed, BoardTAU generates a digital Reservation Receipt (accessible via your reservations dashboard). There is no digital lease contract generated by our platform. Instead, you will show this digital receipt to the landlord upon arrival for verification, and any formal physical lease agreements will be signed on-site.',
  },
  {
    category: 'Payments & Billing',
    title: 'Are there hidden service fees when booking?',
    content: 'BoardTAU believes in full transparency. The amount you see at checkout includes the required reservation fee (which is typically deducted from your first month\'s rent by the landlord) plus a standard processing fee charged by Stripe or PayMongo. There are no hidden markup fees from BoardTAU.',
  },
  {
    category: 'Payments & Billing',
    title: 'Do I pay my monthly rent through BoardTAU?',
    content: 'Currently, BoardTAU only handles the initial, secure Reservation Fee to guarantee your room slot. Ongoing monthly rent payments, utility bills, and security deposits must be paid directly to your landlord based on the physical lease contract you sign upon move-in.',
  },

  // HOST OPERATIONS
  {
    category: 'Host Operations',
    title: 'How do I manage my property listings and rooms?',
    content: 'Landlords have access to a dedicated Analytics Dashboard. From there, you can create and manage property listings, define house rules, upload high-resolution images (stored securely via EdgeStore), and manage individual room units. You can update room availability in real-time to prevent double-booking.',
  },
  {
    category: 'Host Operations',
    title: 'Can landlords process walk-in bookings manually?',
    content: 'Yes! BoardTAU allows landlords to manually add walk-in tenants through their dashboard. This helps owners maintain an accurate, centralized record of all occupied rooms and financial transactions, even for tenants who did not book directly through the web platform.',
  },
  {
    category: 'Host Operations',
    title: 'How many photos can I upload for my listing?',
    content: 'We encourage landlords to upload high-quality images of the bedroom, bathroom, kitchen, and property exterior. Our platform uses EdgeStore to securely host your images. While there is no strict limit, we recommend at least 5 to 7 well-lit photos to attract more student tenants.',
  },
  {
    category: 'Host Operations',
    title: 'Can I temporarily pause or hide my listing?',
    content: 'Yes. If your boarding house is fully occupied, undergoing renovations, or temporarily unavailable, you can toggle your listing visibility in the Analytics Dashboard. This hides it from search results without deleting your reviews or property data.',
  },
  {
    category: 'Host Operations',
    title: 'How does the Analytics Dashboard help my business?',
    content: 'The Analytics Dashboard provides landlords with powerful, real-time insights. You can track total profile views, monitor your booking conversion rates, track your monthly reservation revenue, and monitor which room types (e.g., solo vs. shared) are performing best.',
  },

  // GENERAL INQUIRIES
  {
    category: 'General Inquiries',
    title: 'How does the AI Assistant (Gemini) help me find a room?',
    content: 'BoardTAU integrates Google Generative AI (Gemini) to power our intelligent comparison module and chatbot. Instead of manually comparing dozens of listings, you can ask the AI for personalized recommendations based on your budget, preferred amenities, and proximity to Tarlac Agricultural University. The AI analyzes real-time listing data to give you the best matches.',
  },
  {
    category: 'General Inquiries',
    title: 'How do I use the Interactive Map to find nearby housing?',
    content: 'We use React Leaflet to provide a highly interactive map module. You can visually browse boarding houses, apartments, and dormitories specifically located near Tarlac Agricultural University. The map dynamically updates as you apply filters (like price range or room type), allowing you to pinpoint exactly how far a property is from the campus gates.',
  },
  {
    category: 'General Inquiries',
    title: 'Is BoardTAU only for Tarlac Agricultural University students?',
    content: 'While our platform’s map, search algorithms, and verified listings are heavily optimized for students and faculty of Tarlac Agricultural University (TAU), anyone seeking long-term accommodation in the nearby vicinity is welcome to register and use the platform to find a home.',
  },
  {
    category: 'General Inquiries',
    title: 'Can I save or bookmark boarding houses I like?',
    content: 'Yes! If you find a boarding house you like but aren\'t ready to pay the reservation fee yet, you can use the "Favorites" or bookmark button. You can then access all your saved listings from your profile to compare them before making a final decision.',
  }
];

export default function HelpCenterContent() {
  const { theme } = useTheme();
  const [mounted, setMounted] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [debouncedSearchQuery, setDebouncedSearchQuery] = useState('');
  const [isSearching, setIsSearching] = useState(false);
  const [expandedArticle, setExpandedArticle] = useState<number | null>(null);
  const [selectedCategory, setSelectedCategory] = useState<string | null>(null);

  useEffect(() => {
    setMounted(true);
    // Smooth scroll to top on mount, typical in BoardTAU dashboard views
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }, []);

  // Secure Debounce: Mitigates quick rapid queries and sanitizes against XSS
  useEffect(() => {
    if (searchQuery.length > 0) {
      setIsSearching(true);
    }
    const timer = setTimeout(() => {
      // Basic sanitization: strip angle brackets to prevent potential raw HTML injection
      const sanitized = searchQuery.replace(/[<>]/g, '');
      setDebouncedSearchQuery(sanitized);
      setIsSearching(false);
    }, 400); // 400ms delay
    
    return () => clearTimeout(timer);
  }, [searchQuery]);

  const isDark = mounted ? theme === 'dark' : false;

  const categories = [
    { name: 'Platform Security & KYC', icon: <ShieldCheck className="w-5 h-5 text-red-500" /> },
    { name: 'Payments & Billing', icon: <CreditCard className="w-5 h-5 text-purple-500" /> },
    { name: 'Host Operations', icon: <Settings className="w-5 h-5 text-green-500" /> },
    { name: 'General Inquiries', icon: <Bot className="w-5 h-5 text-blue-500" /> },
  ];

  // Real-time filtering logic based on Debounced Search
  const filteredArticles = allArticles.filter(article => {
    const matchesSearch = article.title.toLowerCase().includes(debouncedSearchQuery.toLowerCase()) || 
                          article.content.toLowerCase().includes(debouncedSearchQuery.toLowerCase());
    const matchesCategory = selectedCategory ? article.category === selectedCategory : true;
    return matchesSearch && matchesCategory;
  });

  return (
    <div className={`min-h-screen ${isDark ? 'bg-slate-900 text-slate-300' : 'bg-gray-50 text-gray-800'}`}>
      
      {/* Hero Section with Search */}
      <div className="pt-32 pb-16 text-center border-b border-neutral-200/50 dark:border-slate-800">
        <div className="container mx-auto px-6 max-w-4xl">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <div className="inline-block px-3 py-1.5 bg-primary/10 dark:bg-primary/20 text-primary rounded-full text-xs font-bold uppercase tracking-wider mb-6">
              Help Center
            </div>
            <h1 className="text-4xl md:text-6xl font-extrabold tracking-tight text-gray-900 dark:text-white mb-4">
              How can we <span className="text-primary">help you?</span>
            </h1>
            <p className="text-lg md:text-xl text-gray-500 dark:text-slate-400 max-w-2xl mx-auto mb-10">
              Search our comprehensive knowledge base for answers regarding bookings, KYC, and platform features.
            </p>
          </motion.div>
          
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.1 }}
            className="relative max-w-2xl mx-auto flex shadow-lg rounded-full overflow-hidden border border-transparent focus-within:border-primary transition-colors bg-white dark:bg-slate-900"
          >
            <div className="flex items-center justify-center pl-6">
              <Search className="w-5 h-5 text-gray-400 dark:text-slate-500" />
            </div>
            <input 
              type="text" 
              value={searchQuery}
              onChange={(e) => {
                setSearchQuery(e.target.value);
                setExpandedArticle(null); // Reset open articles on search
              }}
              placeholder="Search for 'KYC', 'Stripe', or 'Gemini'..." 
              className="w-full py-4 pl-4 pr-4 outline-none bg-transparent text-gray-900 dark:text-white placeholder-gray-400 dark:placeholder-slate-500"
            />
            <div className="flex items-center pr-6">
              {isSearching ? (
                <Loader2 className="w-5 h-5 text-primary animate-spin" />
              ) : searchQuery ? (
                <button 
                  onClick={() => setSearchQuery('')}
                  className="text-gray-400 hover:text-primary dark:text-slate-500 dark:hover:text-primary transition-colors"
                >
                  <X className="w-5 h-5" />
                </button>
              ) : null}
            </div>
          </motion.div>
        </div>
      </div>

      {/* Main Content Area */}
      <div className="container mx-auto max-w-4xl px-6 py-12">
        
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-50px" }}
          transition={{ duration: 0.6, ease: "easeOut" }}
        >
          <h2 className="text-2xl font-bold mb-6 text-gray-900 dark:text-white">
            Explore by Category
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-16">
            {categories.map((cat, idx) => (
              <button
                key={cat.name}
                onClick={() => {
                  setSelectedCategory(selectedCategory === cat.name ? null : cat.name);
                  setExpandedArticle(null);
                }}
                className={`flex items-center p-4 rounded-xl border transition-all duration-300 group
                  ${selectedCategory === cat.name 
                    ? 'border-primary bg-primary/5 ring-1 ring-primary' 
                    : isDark 
                      ? 'bg-slate-800 border-slate-700 hover:border-slate-500 hover:bg-slate-700/50' 
                      : 'bg-white border-gray-200 hover:border-primary/30 hover:bg-gray-50 hover:shadow-md'
                  }
                `}
              >
                <div className={`p-3 rounded-lg mr-4 transition-colors ${selectedCategory === cat.name ? 'bg-primary/10' : isDark ? 'bg-slate-700 group-hover:bg-slate-600' : 'bg-gray-100 group-hover:bg-primary/5'}`}>
                  {cat.icon}
                </div>
                <div className="text-left flex-grow">
                  <h3 className={`font-semibold ${isDark ? 'text-white' : 'text-gray-900'}`}>{cat.name}</h3>
                  <p className={`text-sm mt-1 ${isDark ? 'text-slate-400' : 'text-gray-500'}`}>
                    {allArticles.filter(a => a.category === cat.name).length} articles
                  </p>
                </div>
                <ArrowRight className={`w-5 h-5 transition-transform ${selectedCategory === cat.name ? 'text-primary translate-x-1' : isDark ? 'text-slate-500' : 'text-gray-300 group-hover:text-primary group-hover:translate-x-1'}`} />
              </button>
            ))}
          </div>
        </motion.div>

        {/* Dynamic Articles Section */}
        <div className="flex items-center justify-between mb-6">
          <h2 className={`text-2xl font-bold ${isDark ? 'text-white' : 'text-gray-900'}`}>
            {searchQuery ? `Search Results (${filteredArticles.length})` : (selectedCategory ? `${selectedCategory} Articles` : 'All Knowledge Base Articles')}
          </h2>
        </div>
        <motion.div 
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-50px" }}
          transition={{ duration: 0.6, ease: "easeOut", delay: 0.1 }}
          className="mb-20"
        >
          <GlowingCards layout="stack" gap="1rem" padding="0" className="w-full">
            {filteredArticles.length > 0 ? (
              filteredArticles.map((article, idx) => {
                const isExpanded = expandedArticle === idx;
                return (
                  <GlowingCard 
                    key={idx} 
                    glowColor="var(--primary-color, #2f7d6d)"
                    className={`!p-0 rounded-xl overflow-hidden
                      ${isDark ? 'bg-slate-800/50 border-slate-700' : 'bg-white border-gray-200'}
                      ${isExpanded ? (isDark ? 'ring-1 ring-slate-600' : 'ring-1 ring-gray-300 shadow-md') : ''}
                    `}
                  >
                    <button 
                      onClick={() => setExpandedArticle(isExpanded ? null : idx)}
                      className="w-full flex items-center justify-between p-5 text-left focus:outline-none"
                    >
                      <div className="flex flex-col pr-4">
                        <span className={`text-[11px] uppercase tracking-wider font-semibold mb-1 ${isDark ? 'text-primary-light' : 'text-primary'}`}>
                          {article.category}
                        </span>
                        <span className={`font-medium text-lg ${isDark ? (isExpanded ? 'text-white' : 'text-slate-300') : (isExpanded ? 'text-black' : 'text-gray-800')}`}>
                          {article.title}
                        </span>
                      </div>
                      <ChevronDown className={`w-5 h-5 flex-shrink-0 transition-transform duration-300 ${isExpanded ? 'rotate-180' : ''} ${isDark ? 'text-slate-400' : 'text-gray-500'}`} />
                    </button>
                    
                    <AnimatePresence>
                      {isExpanded && (
                        <motion.div
                          initial={{ height: 0, opacity: 0 }}
                          animate={{ height: 'auto', opacity: 1 }}
                          exit={{ height: 0, opacity: 0 }}
                          transition={{ duration: 0.3, ease: "easeInOut" }}
                        >
                          <div className={`p-6 border-t ${isDark ? 'border-slate-700 text-slate-300' : 'border-gray-100 text-gray-600'} leading-relaxed text-base`}>
                            {article.content}
                          </div>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </GlowingCard>
                );
              })
            ) : (
              <div className={`text-center py-12 rounded-xl border border-dashed ${isDark ? 'border-slate-700 bg-slate-800/50' : 'border-gray-300 bg-gray-50'}`}>
                <Search className={`w-10 h-10 mx-auto mb-4 opacity-50 ${isDark ? 'text-slate-400' : 'text-gray-400'}`} />
                <p className={`text-lg font-medium ${isDark ? 'text-white' : 'text-gray-900'}`}>No articles found</p>
                <p className={`mt-2 ${isDark ? 'text-slate-400' : 'text-gray-500'}`}>
                  Try adjusting your search query or selecting a different category.
                </p>
              </div>
            )}
          </GlowingCards>
        </motion.div>

      </div>
    </div>
  );
}
